### ISSUE TITLE
Documentation to create Solid user interfaces for a developer audience

### ISSUE THREAD

**Issue by PSFW** [w3c/EasierRDF#105]
The SolidOS (Social Linked Data OS) project exposes multiple efforts for creating user interfaces:

- [Solid Panes](https://github.com/SolidOS/solid-panes) - Allows for creating composable user interfaces dependant on what type of data is being displayed (similar to Android OS with it's Intent system)
- [Solid UI](https://github.com/SolidOS/solid-ui) - Exposes Forms functionality for data input
- [Solid UIX](https://github.com/SolidOS/solid-uix) - Exposes functionality for querying SPARQL endpoints (or in-memory stores) and displaying those results within templates

These are all great efforts but there is no documented route through to use these libraries in combination to actually create a working interface, it all seems theoretical at the moment. This should be as simple as possible to drive adoption of this technology but at the moment there doesn't seem to be any cohesion. A [userguide](https://github.com/SolidOS/userguide) exists for SolidOS but it stops short of explaining how a developer could create an 'app-like experience'. We even have a complicated Form playground that [is not clear on how to use it](https://github.com/SolidOS/form-playground/issues/10). 

SolidOS has alot of promise and it's clear to see why people would want to get involved, but there is too much context to sift through to try to get a small app working on it. I have really struggled to make sense of it and to know where to start, and I've still to date have not created an interface on top of Solid.

**Comment by afs** [comment]
Maybe this isn't the best repo to get this issue seen.

Have you considered https://forum.solidproject.org/ or the gitter room for Solid app https://app.gitter.im/#/room/#solid_app-development:gitter.im ?

**Comment by PSFW** [comment]
thank you for your response @afs, I will try there instead. My thinking was that this repo is dedicated to lowering the barrier for working with RDF, and I suppose I thought Solid would really help to do that. I will move this to the mentioned repo, thanks a again or your help

**Comment by afs** [comment]
It is about lowering the barriers in general but specific points about Solid may not get discussion in this repo because there are specific forums for Solid.
