### ISSUE TITLE
move SPARQL-related issues to https://github.com/w3c/sparql-12/issues

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/EasierRDF#67]
@dbooth-boston Could you move SPARQL-related issues from here to https://github.com/w3c/sparql-12/issues ?
I think Github recently added a feature to move issues.

**Comment by np00** [comment]
Cool, I did not know about this. I just asked to join the W3C Community Group: https://www.w3.org/community/sparql-12/

Maybe you should share it in the sem-web mailing list :)

**Comment by dbooth-boston** [comment]
Yes, I think that is a good idea.  I'll see if I can figure out how to do it.

**Comment by dbooth-boston** [comment]
Ok, I think I have transferred all of them, so I will close this issue.  FYI #39 (SPARQL Triplestore and Reasoning Performance) is more a complaint about tools than the SPARQL standard, so I'm leaving that one.
