### ISSUE TITLE
Namespaces linked to within RDF can have broken links

### ISSUE THREAD

**Issue by PSFW** [w3c/EasierRDF#94]
Namespaces that are included in RDF examples can have broken links for example in [this documentation](https://www.w3.org/2004/12/q/doc/rdf-labels.html#:~:text=http://www.icra.org/rdfs/vocabularyv03#lz). Could decentralisation help with this? i.e. [IPFS](https://ipfs.io/). Having hashed links for ontologies could have a helpful side effect with versioning too.

As a beginner discovery is difficult when you have well formed ontologies that then link to namespaces that no longer exist.

**Comment by PSFW** [comment]
After further research (and being ignored here), I've found a possible solution to this in [Decentralised Mutable Containers - Content Addressing](https://web.archive.org/web/20210731213417/https://inqlab.net/projects/dmc/#_content_addressing), which ironically also is a broken link, hence the Wayback Machine link. Decentralised Mutable Containers allow you to address RDF content in _fragment graphs_, which can then be stored for example in IPFS.

I can't be the only person that is frustrated with the amount of broken links in documentation, but I am obviously the only person that thinks this is a barrier for RDF. I am closing this issue.

**Comment by dbooth-boston** [comment]
The problem of broken links is not specific to RDF, so I didn't feel like I had anything useful to add about it.
